services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: jackdiva/meeting-rag-api:latest
    container_name: meeting_rag_api
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-qwen/qwen3-32b}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - JSON_DIR=/app/data/json_chunks
      - VECTOR_DB_DIR=/app/meetingbank_vector_db
      - WHOOSH_DIR=/app/whoosh_cache
    restart: unless-stopped

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: jackdiva/meeting-rag-react:latest
    container_name: meeting_rag_react
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    restart: unless-stopped